Repository Ensembl/ensembl-production-services, pull requests merged in 2020-08, with the labels that each got.

#95 fixing Django wrong time displayed
  production_services/settings.py
  production_services/settings_tests.py
Labels: bug

#96 Fix bug when all the tables have been copied but that flush, optimize…
  ensembl_dbcopy/models.py
  ensembl_dbcopy/templates/admin/dbcopy/detail.html
Labels: bug, enhancement

#97 Added division specific information for FAQ record in ensembl_website…
  ensembl_website/admin.py
  ensembl_website/models.py
Labels: enhancement

#98 Features/kb extension
  .gitignore
  .travis.yml
  ensembl_bugs/templates/known_bugs.html
  ensembl_bugs/templates/known_bugs_export.html
  ensembl_bugs/templates/known_bugs_table.html
  ensembl_bugs/urls.py
  ensembl_bugs/views.py
  ensembl_dbcopy/api/views.py
  ensembl_dbcopy/api/viewsets.py
  ensembl_dbcopy/fixtures/ensembl_dbcopy.json
  ensembl_dbcopy/static/js/multiselect.js
  ensembl_dbcopy/tests.py
  ensembl_intentions/__init__.py
  ensembl_intentions/admin.py
  ensembl_intentions/apps.py
  ensembl_intentions/migrations/0001_initial.py
  ensembl_intentions/migrations/__init__.py
  ensembl_intentions/models.py
  ensembl_intentions/templates/intention.html
  ensembl_intentions/templates/intentions_export.html
  ensembl_intentions/templates/intentions_table.html
  ensembl_intentions/templates/jira_issue_list.html
  ensembl_intentions/templates/knownbug.html
  ensembl_production/admin.py
  ensembl_production/templates/admin/base.html
  ensembl_production/views.py
  manage.py
  production_services/settings.py
  production_services/settings_tests.py
  production_services/urls.py
Labels: enhancement

#103 Bugfixes/redirect perms outreach
  ensembl_intentions/admin.py
  production_services/urls.py
Labels: bug
