Repository Ensembl/ensembl-production-services, pull requests merged in 2020-06, with the labels that each got.

#84 Filter web data on their id.
  ensembl_production_db/models.py
Labels: enhancement

#87 Copy service improvements 2
  ensembl_dbcopy/admin.py
  ensembl_dbcopy/fixtures/ensembl_dbcopy.json
  ensembl_dbcopy/forms.py
  ensembl_dbcopy/migrations/0002_adding_request_date.py
  ensembl_dbcopy/models.py
  ensembl_dbcopy/static/css/db_copy.css
  ensembl_dbcopy/templates/admin/dbcopy/detail.html
  ensembl_production/migrations/0009_meta_option.py
  requirements.txt
Labels: bug, enhancement

#88 Merge master june
  ensembl_dbcopy/admin.py
  ensembl_dbcopy/fixtures/ensembl_dbcopy.json
  ensembl_dbcopy/forms.py
  ensembl_dbcopy/migrations/0002_adding_request_date.py
  ensembl_dbcopy/models.py
  ensembl_dbcopy/static/css/db_copy.css
  ensembl_dbcopy/templates/admin/dbcopy/detail.html
  ensembl_production/migrations/0009_meta_option.py
  ensembl_production_db/admin.py
  ensembl_production_db/models.py
  requirements.txt
Labels: enhancement

#90 Removed the reset failed job button since DBA have 3 auto retry and n…
  ensembl_dbcopy/templates/admin/dbcopy/detail.html
  ensembl_dbcopy/urls.py
  ensembl_dbcopy/views.py
  production_services/settings.py
  production_services/settings_tests.py
Labels: bau, bug
