Repository Ensembl/ensembl-production-services, pull requests merged in 2020-03, with the labels that each got.

#71 Release/100 merged back onto master
  ensembl_dbcopy/admin.py
  ensembl_production/templates/inc/footer.inc.html
  production_services/settings.py
  production_services/urls.py
Labels: enhancement

#72 Fixed 500 when trying to add a new app.
  ensembl_production/admin.py
Labels: bug

#73 Copy service improvements
  ensembl_dbcopy/admin.py
  ensembl_dbcopy/forms.py
  ensembl_dbcopy/models.py
  ensembl_dbcopy/static/css/db_copy.css
  ensembl_dbcopy/static/js/multiselect.js
  ensembl_dbcopy/templates/admin/dbcopy/detail.html
  ensembl_dbcopy/templates/admin/dbcopy/submit.html
  ensembl_dbcopy/templates/list.html
  ensembl_dbcopy/templates/submit.html
  ensembl_dbcopy/urls.py
  ensembl_dbcopy/views.py
  ensembl_production/admin.py
  production_services/settings.py
Labels: bug, enhancement

#74 Release/100
  ensembl_production/admin.py
Labels: bau
