Repository Ensembl/ensembl-production-services, pull requests merged in 2020-02, with the labels that each got.

#51 Release/100
  .env.dist
  NOTICE
  production_services/settings.py
Labels: enhancement

#52 Corrected typo in settings.py
  production_services/settings.py
Labels: enhancement

#53 Simplify test settings (not override everything)
  production_services/settings_tests.py
Labels: enhancement

#54 Release/100
  .gitignore
  .travis.yml
  ensembl_production/fixtures/elastic_hq.json
  ensembl_production/migrations/0001_initial.py
  ensembl_production/migrations/0005_update_flask_apps.py
  ensembl_production/migrations/0006_update_admin_menus.py
  ensembl_production/models.py
  ensembl_production/router.py
  ensembl_production/static/css/home.css
  ensembl_production/static/css/production_admin.css
  ensembl_production/static/js/bootstrap.js
  ensembl_production/static/js/bootstrap.min.js
  ensembl_production/templates/admin/base.html
  ensembl_production/templates/admin/checkbox_option.html
  ensembl_production/templates/inc/menu_bar.inc.html
  ensembl_production/utils.py
  ensembl_production_db/admin.py
  ensembl_production_db/api/serializers.py
  ensembl_production_db/api/viewsets.py
  ensembl_production_db/migrations/0002_auto_20190924_1613.py
  ensembl_production_db/migrations/0004_json_field_updates.py
  ensembl_production_db/models.py
  ensembl_production_db/router.py
  ensembl_production_db/tests.py
  ensembl_website/admin.py
  production_services/settings.py
  production_services/settings_tests.py
  requirements.txt
Labels: bau

#55 Features/django jsonfield
  ensembl_production/models.py
  ensembl_production_db/admin.py
  ensembl_production_db/api/serializers.py
  ensembl_production_db/models.py
  ensembl_production_db/tests.py
  requirements.txt
Labels: bug

#56 Release/100
  ensembl_production/models.py
  ensembl_production_db/admin.py
  ensembl_production_db/api/serializers.py
  ensembl_production_db/models.py
  ensembl_production_db/tests.py
  requirements.txt
Labels: bau

#57 Fix new AnalysisDescription admin page error
  ensembl_production/static/css/production_admin.css
  ensembl_production_db/admin.py
Labels: bug

#58 Release/100
  ensembl_production/static/css/production_admin.css
  ensembl_production_db/admin.py
Labels: bau

#59 Make TextField store NULL instead of empty string to be consistent wi…
  ensembl_production_db/migrations/0005_text_field_null_update.py
  ensembl_production_db/models.py
  ensembl_website/migrations/0004_make_page_url_required.py
  ensembl_website/models.py
Labels: enhancement

#62 Field is_current enable in ExternalDB Admin page
  ensembl_production/static/css/production_admin.css
  ensembl_production_db/admin.py
  ensembl_production_db/models.py
Labels: bug

#60 Known bugs
  ensembl_bugs/__init__.py
  ensembl_bugs/apps.py
  ensembl_bugs/templates/known_bugs.html
  ensembl_bugs/templates/known_bugs_export.html
  ensembl_bugs/templates/known_bugs_table.html
  ensembl_bugs/urls.py
  ensembl_bugs/views.py
  ensembl_production/admin.py
  ensembl_production/apps.py
  ensembl_production/migrations/0007_credentials.py
  ensembl_production/models.py
  manage.py
  production_services/settings.py
  production_services/urls.py
  requirements.txt
Labels: enhancement

#63 Disable USE_X_FORWARDED_HOST
  production_services/settings.py
Labels: enhancement

#66 Adding new User admin action to deactivate multiple users. Removed De…
  ensembl_production/admin.py
Labels: enhancement

#67 Fixing delete user button. We should not use it since we want to keep…
  ensembl_production/models.py
Labels: bug
