Repository Ensembl/ensembl-production-services, pull requests merged in 2021-03, with the labels that each got.

#123 ENSRR-142 - updated query not to fetch Resolved / Done / Closed
  ensembl_intentions/models.py
Labels: enhancement

#125 Merge back stable onto master
  ensembl_dbcopy/admin.py
  ensembl_dbcopy/forms.py
  ensembl_dbcopy/migrations/0005_targethostgroup.py
  ensembl_dbcopy/models.py
  ensembl_dbcopy/static/js/multiselect.js
  ensembl_intentions/models.py
Labels: bau

#128 required flag set to false for target host dropdown which was blockin…
  ensembl_dbcopy/forms.py
Labels: bug
